// Generated by https://quicktype.io

export interface Contact {
    id: number;
    name: string;
    email: string;
    nit: string;
    namePunto: string;
    ciudad: string;
    promotor: string;
    rtc: string;
    tratamientoDatos: boolean;
    createdAt: string;
}